# Generated by Django 5.0.1 on 2024-02-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userdata_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='transactions',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
