# Generated by Django 5.0.1 on 2024-02-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
