# Generated by Django 5.0.1 on 2024-02-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_remove_userdata_status_remove_userdata_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('total_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('friends', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('status_paid', models.BooleanField(default=False)),
                ('status_unpaid', models.BooleanField(default=False)),
                ('transactions', models.ManyToManyField(to='api.transaction')),
            ],
        ),
    ]
